version: 0.1

phases:
  install:
    commands:
      - printenv
      - npm install
  build:
    commands:
      - npm run test
  post_build:
    commands:
      - npm install -g serverless
      - serverless -v deploy
